### ISSUE TITLE
Please improve the pull request instructions

### ISSUE THREAD

**Issue by matentzn** [OBOAcademy/obook#189] opened 2022-06-17 08:22 UTC
This needs to be really improved: https://github.com/OBOAcademy/obook/blob/master/docs/howto/github-create-pull-request.md

The goal is to collect best practices to write a pull request in general (irrespective of the change).

# Technical
1. Switch branch
2. push to branch (update from master?)

# Practice
1. All pull requests must have an associated issue
1. Give a very descriptive title
1. Write a great summary of what the change is, referring to the issue. The sentence should clearly state how the issue is addressed

Make this really nice. I intend to share this across all ontology repos in the contribution guidelines.

**Comment by matentzn** [comment] 2022-06-17 13:47
Some other notes to get inspired from @cthoyt : https://github.com/cthoyt/cookiecutter-snekpack/blob/main/%7B%7Bcookiecutter.package_name%7D%7D/.github/CONTRIBUTING.md 

Its focused on software but maybe some useful bits that apply to ontologies

**Comment by cthoyt** [comment] 2022-06-17 14:11
See also the Bioregistry's contribution guidelines. Lots of effort went into that describing who can make contributions, how, etc. and it's more focused on content contribution (both in the form of code and suggestions)

https://github.com/biopragmatics/bioregistry/blob/main/docs/CONTRIBUTING.md

**Comment by matentzn** [comment] 2022-06-17 14:18
Beautiful one, yes, lets use this to forge our own! Thank you!

**Comment by nicolevasilevsky** [comment] 2022-06-17 22:36
> Practice
All pull requests must have an associated issue
Give a very descriptive title
Write a great summary of what the change is, referring to the issue. The sentence should clearly state how the issue is addressed

I made some edits to address these changes ⬆️ : https://github.com/OBOAcademy/obook/blob/master/docs/howto/github-create-pull-request.md

**Comment by matentzn** [comment] 2022-06-18 12:54
Nice. Can we add a bit of fluff to the beginning to say what a pull request is, why we need it and how to switch to a branch?

**Comment by matentzn** [comment] 2022-07-20 15:03
@nicolevasilevsky 

Your lesson looks very nice, thanks!! Looking forward to seeing it.

I would like to see two things a bit more detailed:

1. How to write really good pill requests in general, i.e. what kind of information to include in the description (good summary, link to the issue, motivation for the chosen solution), how to write a great descriptive title.
2. How to properly deal with reviews. I think people are still not clear what they need to do when they get assigned a PR for review. What should they look out for? When do they know they are done with the review? What kind of person do we need for what kind of pull request? How should they request changes? This inline "suggest changes" functionality on PRs - we don't use it much, but should. Generally, we need code reviews to cover for imperfections in automated CI - so no reviewer needs to look for unsatisfiable classes, but they may have to look for badly written definitions.

**Comment by nicolevasilevsky** [comment] 2022-07-20 15:24
will do! thanks for the feedback :)

**Comment by nicolevasilevsky** [comment] 2022-07-20 23:37
@matentzn I tried to address all your feedback, let me know what you think:
https://oboacademy.github.io/obook/tutorial/pull-requests/
thanks!

**Comment by nicolevasilevsky** [comment] 2022-11-17 16:25
talking to Nico, we can close this

**Closed by nicolevasilevsky** 2022-11-17 16:25 UTC
Labels: need-volunteer
